# Generated by Django 3.1.6 on 2021-02-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20210217_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='id_base62',
            new_name='slug',
        ),
    ]
