# Generated by Django 3.1.6 on 2021-02-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id_base62',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
